server:
  port: 80
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhou0000/config-repo
          username: zhou0000
          password: Zhou@0086
          search-paths: /config-demo #子目录
          basedir: G:\product\configManage\config-server\basedir #config server会从远端git拉取一份到本地
      profile: dev
  rabbitmq:
    host: 192.168.117.128
    port: 5672
    username: zhou01
    password: zhou01
    virtual-host: /leyou
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        #include: "bus-refresh"
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka