server:
  port: 10087
spring:
  application:
    name: client-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhou0000/config-repo
          username: zhou0000
          password: Zhou@0086
          search-paths: /config-demo #子目录
          basedir: G:\product\configManage\config-server\basedir #config server会从远端git拉取一份到本地
      profile: dev
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka